"""Agent Memory Toolkit – local and cloud agent memory management."""

from azure.cosmos.agent_memory._authz import (
    AuthzQueryPredicate,
    AuthzResolution,
    ScopeAccessDecision,
    caller_subjects,
    can,
    resolve_scope_access,
)
from azure.cosmos.agent_memory._security import SecurityContext
from azure.cosmos.agent_memory.aio import AsyncCosmosMemoryClient
from azure.cosmos.agent_memory.chat import ChatClient
from azure.cosmos.agent_memory.cosmos_memory_client import CosmosMemoryClient
from azure.cosmos.agent_memory.exceptions import (
    AgentMemoryError,
    ConfigurationError,
    CosmosNotConnectedError,
    CosmosOperationError,
    LLMError,
    MemoryConflictError,
    MemoryNotFoundError,
    MemoryTypeMismatchError,
    SharedRecordReadOnlyError,
    ValidationError,
)
from azure.cosmos.agent_memory.models import (
    MemoryAcl,
    MemoryCurationStatus,
    MemoryProvenance,
    MemoryRecord,
    MemoryRole,
    MemoryScopeType,
    MemoryType,
    SearchResult,
)
from azure.cosmos.agent_memory.processors import (
    DurableFunctionProcessor,
    InProcessProcessor,
    MemoryProcessor,
    ProcessThreadResult,
    UserSummaryResult,
)
from azure.cosmos.agent_memory.thresholds import (
    DEFAULT_EPISODE_EVAL_EVERY_N,
    DEFAULT_EPISODE_IDLE_GAP_SECONDS,
    DEFAULT_EPISODE_MAX_TURNS,
    DEFAULT_EPISODE_MIN_TURNS,
    DEFAULT_EPISODE_TOPIC_DRIFT,
    DEFAULT_FACT_EXTRACTION_EVERY_N,
    DEFAULT_THREAD_SUMMARY_EVERY_N,
    DEFAULT_USER_SUMMARY_EVERY_N,
    PROCESSOR_OWNER_DURABLE,
    PROCESSOR_OWNER_INPROCESS,
    get_episode_eval_every_n,
    get_episode_idle_gap_seconds,
    get_episode_max_turns,
    get_episode_min_turns,
    get_episode_topic_drift,
    get_fact_extraction_every_n,
    get_processor_owner,
    get_thread_summary_every_n,
    get_user_summary_every_n,
)

__all__ = [
    "CosmosMemoryClient",
    "AsyncCosmosMemoryClient",
    "ChatClient",
    "MemoryCurationStatus",
    "MemoryAcl",
    "MemoryProvenance",
    "MemoryRecord",
    "MemoryRole",
    "MemoryScopeType",
    "MemoryType",
    "SearchResult",
    "SecurityContext",
    "AuthzQueryPredicate",
    "AuthzResolution",
    "ScopeAccessDecision",
    "caller_subjects",
    "can",
    "resolve_scope_access",
    "MemoryProcessor",
    "InProcessProcessor",
    "DurableFunctionProcessor",
    "ProcessThreadResult",
    "UserSummaryResult",
    "AgentMemoryError",
    "ConfigurationError",
    "CosmosNotConnectedError",
    "CosmosOperationError",
    "LLMError",
    "MemoryConflictError",
    "MemoryNotFoundError",
    "SharedRecordReadOnlyError",
    "MemoryTypeMismatchError",
    "ValidationError",
    "DEFAULT_EPISODE_EVAL_EVERY_N",
    "DEFAULT_EPISODE_IDLE_GAP_SECONDS",
    "DEFAULT_EPISODE_MAX_TURNS",
    "DEFAULT_EPISODE_MIN_TURNS",
    "DEFAULT_EPISODE_TOPIC_DRIFT",
    "DEFAULT_FACT_EXTRACTION_EVERY_N",
    "DEFAULT_THREAD_SUMMARY_EVERY_N",
    "DEFAULT_USER_SUMMARY_EVERY_N",
    "PROCESSOR_OWNER_DURABLE",
    "PROCESSOR_OWNER_INPROCESS",
    "get_episode_eval_every_n",
    "get_episode_idle_gap_seconds",
    "get_episode_max_turns",
    "get_episode_min_turns",
    "get_episode_topic_drift",
    "get_fact_extraction_every_n",
    "get_processor_owner",
    "get_thread_summary_every_n",
    "get_user_summary_every_n",
]
